- type: job
  id: NanotrasenRepresentative
  name: Nanotrasen Representative
  description: "Represent NT, Send reports back to them on the station's situation, Inform the heads of anything CentCom orders them to do."
  playTimeTracker: JobNanotrasenRepresentative
  requirements:
    - !type:DepartmentTimeRequirement
      department: Command
      time: 180000  #50 hours
    - !type:AgeRequirement
      requiredAge: 21
  weight: 20
  startingGear: NanotrasenRepresentativeGear
  icon: "JobIconNanotrasenRepresentative"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  whitelisted: true
  access:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: NanotrasenRepresentativeGear
  equipment:
    id: CentcomPDA
    ears: ClothingHeadsetCentCom
    pocket1: WeaponPistolN1984
    pocket2: CaneSheathFilledNanotrasen
  storage:
    back:
    - RubberStampCentcom
    - BaseMagazineMagnum
